name: EduCraft
version: VERSION
main: de.craften.plugins.educraft.EduCraft

commands:
  ec:
    description: EduCraft main command.

permissions:
  educraft.run:
    default: true
  educraft.stop:
    default: true
  educraft.stop.any:
    default: op
  educraft.reset:
    default: true
